#!/bin/bash

. lib/init.sh

# Terminate execution on command failure
set -e

echo "About to connect via ssh to upgrade your cluster. Press enter to continue."
read

open_ssh

remote_exec "if [ ! -d phabricator ]; then git clone https://github.com/nothingheremovealong/phabricator.git; else cd phabricator; git fetch; git rebase origin/master; fi" || exit 1
remote_exec "cd /opt;bash ~/phabricator/vm/upgrade.sh" || exit 1
