runtime: custom
vm: true
api_version: 1
threadsafe: yes

manual_scaling:
  instances: 1

builtins:
- appstats: on

network:
  name: phabricator

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /api/.*
  script: dynamic

- url: /res/.*
  script: dynamic

- url: /file/.*
  script: dynamic

- url: /ws/.*
  script: dynamic

- url: /auth/register/
  script: dynamic
#  secure: always
  login: admin

- url: /.*
  script: dynamic
  login: admin
#  secure: always
