runtime: custom
vm: true
api_version: 1
threadsafe: yes

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

builtins:
- appstats: on

network:
  name: phabricator

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /api/.*
  script: dynamic

- url: /res/.*
  script: dynamic

- url: /file/data/.*
  script: dynamic

- url: /ws/.*
  script: dynamic

- url: /auth/register/
  script: dynamic
  #login: admin

- url: /.*
  script: dynamic
  #login: admin
